import { Inter } from 'next/font/google'
import './globals.css'
import GlobalState from '@/src/context'
import Header from '@/src/components/header'
import Sidebar from '@/src/components/sidebar'
import NextAuthProvider from '@/src/auth-provider'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Website mua ho',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
       <body className={inter.className}>
        <NextAuthProvider>
           <GlobalState>
       <div className="flex h-screen overflow-hidden bg-[#f7f7f9]">
            <div>
              <Sidebar />
            </div>
            
            <div className="relative flex flex-1 flex-col overflow-y-auto overflow-x-hidden">
              <Header />
               <main className="mx-auto max-w-screen-2xl p-4 md:p-6 2xl:p-10 absolute mt-12 ">
                {children}
              </main>
           </div>
          </div>
        </GlobalState>
        </NextAuthProvider>
      
      </body>
    </html>
  )
}
